# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
    types: [published]
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    # Runs a single command using the runners shell
    - name: Export digest
      run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
          ls /tmp/digests
    - name: bump version
      run: | 
        perl -i -pe 's/(\$plugin->version\s*=\s*)(\d+)/$1.($2+1)/e' version.php
        cp -r . /tmp/digests
    - name: Upload digest
      uses: actions/upload-artifact@v3
      with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
